# Generated by Django 4.2.7 on 2023-11-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargofuncionario',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente'), ('MECANICO', 'Mecanico'), ('MECANICO ATENDENTE', 'Mecanico atendente')], max_length=18),
        ),
    ]
