# Generated by Django 4.2.7 on 2023-11-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_alter_funcionario_cargofuncionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ordensdeservico',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargofuncionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cargo'),
        ),
    ]
