# Generated by Django 4.2.7 on 2023-11-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_remove_funcionario_ordensdeservico_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ordensdeservico',
            field=models.ManyToManyField(to='aplic.ordemdeservico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargofuncionario',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente'), ('MECANICO', 'Mecanico'), ('MECANICO ATENDENTE', 'Mecanico atendente')], max_length=18),
        ),
    ]
