# Generated by Django 4.2.7 on 2023-11-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_funcionario_ordensdeservico_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargofuncionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(to='aplic.cargo'),
        ),
    ]
