# Generated by Django 4.2.7 on 2023-11-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_remove_funcionario_cargofuncionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='ImagemPeca',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/'),
        ),
    ]
