# Generated by Django 4.2.7 on 2023-11-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_peca_imagempeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='ImagemOs',
            field=models.ImageField(blank=True, null=True, upload_to='os/'),
        ),
    ]
