# Generated by Django 4.2.7 on 2023-11-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_remove_funcionario_cargos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo_individual',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargos_multiplos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(to='aplic.cargo'),
        ),
    ]
