# Generated by Django 4.2.7 on 2023-11-30 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0010_remove_funcionario_cargo_individual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cargo', to='aplic.cargo'),
        ),
    ]
