# Generated by Django 4.2.7 on 2023-11-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_remove_funcionario_cargos_funcionario_cargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(related_name='funcionarios', to='aplic.cargo'),
        ),
    ]
