# Generated by Django 4.2.7 on 2023-11-30 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0012_remove_funcionario_cargos_funcionario_cargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_individual', to='aplic.cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos_multiplos',
            field=models.ManyToManyField(related_name='funcionarios_multiplos', to='aplic.cargo'),
        ),
    ]
